### ISSUE TITLE
Poster Review

### ISSUE THREAD

**Issue by samgdotson** [arfc/2019-dotson-winter#2]
This issue can be closed when the poster content and style are deemed adequate.

[2019-dotson-answinter.pdf](https://github.com/arfc/2019-dotson-winter/files/3838874/2019-dotson-answinter.pdf)

**Comment by katyhuff** [comment]
Can you try making it  in latex on a white background with an emphasis on increasing the size of the figures? There's a poster template somewhere in the arfc org. 

- needs to convert to block I logo (not old column I).. I think the current template might do this right... but not sure. 
- all figures need numbered captions
- You can drop "dr" from my name
- Consider using bold text here and there to emphasize key words.

**Comment by samgdotson** [comment]
I have pushed the poster to my fork with the desired changes.
